import json
from pathlib import Path
from datetime import datetime

REPORT_JSON = Path("reports/drift_report.json")
REPORT_HTML = Path("reports/drift_report.html")


def generate_report():
    with open(REPORT_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    status = data.get("status", "UNKNOWN")
    resource = data.get("resource", "Unknown")
    region = data.get("region", "Unknown")

    risk = data.get("risk", {})
    risk_level = risk.get("level", "LOW")
    risk_score = risk.get("score", 0)
    reason = risk.get("reason", "No security risk detected")

    added_rules = data.get("added_rules", [])
    removed_rules = data.get("removed_rules", [])

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if status == "DRIFT_DETECTED":
        status_text = "DRIFT DETECTED"
        action = "BUILD BLOCKED"
    else:
        status_text = "NO DRIFT"
        action = "BUILD PASSED"

    added_html = ""

    if added_rules:
        for rule in added_rules:
            added_html += f"""
            <tr>
                <td>{rule.get("protocol", "-").upper()}</td>
                <td>{rule.get("from_port", "-")}</td>
                <td>{rule.get("to_port", "-")}</td>
                <td>{rule.get("cidr", "-")}</td>
                <td>{rule.get("risk", {}).get("level", "-")}</td>
            </tr>
            """
    else:
        added_html = """
        <tr>
            <td colspan="5">No unauthorized rules detected</td>
        </tr>
        """

    removed_html = ""

    if removed_rules:
        for rule in removed_rules:
            removed_html += f"""
            <tr>
                <td>{rule.get("protocol", "-").upper()}</td>
                <td>{rule.get("from_port", "-")}</td>
                <td>{rule.get("to_port", "-")}</td>
                <td>{rule.get("cidr", "-")}</td>
            </tr>
            """
    else:
        removed_html = """
        <tr>
            <td colspan="4">No removed rules</td>
        </tr>
        """

    html = f"""
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">

<title>DriftGuard Security Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background: #f4f6f8;
    margin: 0;
    padding: 40px;
}}

.container {{
    max-width: 1000px;
    margin: auto;
    background: white;
    padding: 35px;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.08);
}}

h1 {{
    margin-bottom: 5px;
}}

.subtitle {{
    color: #666;
}}

.status {{
    padding: 18px;
    margin: 25px 0;
    border-radius: 8px;
    font-size: 22px;
    font-weight: bold;
}}

.status.drift {{
    background: #ffe5e5;
    color: #b00020;
}}

.status.clean {{
    background: #e5f7e9;
    color: #16733b;
}}

.cards {{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 15px;
    margin: 25px 0;
}}

.card {{
    padding: 20px;
    background: #f7f8fa;
    border-radius: 8px;
}}

.card-title {{
    color: #666;
    font-size: 14px;
}}

.card-value {{
    font-size: 24px;
    font-weight: bold;
    margin-top: 8px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    margin: 15px 0 30px;
}}

th, td {{
    padding: 12px;
    border-bottom: 1px solid #ddd;
    text-align: left;
}}

th {{
    background: #f1f3f5;
}}

.reason {{
    background: #fff7e6;
    padding: 15px;
    border-radius: 8px;
}}

.footer {{
    margin-top: 30px;
    color: #777;
    font-size: 13px;
}}

</style>

</head>

<body>

<div class="container">

<h1>🛡️ DriftGuard Security Report</h1>

<div class="subtitle">
Infrastructure Drift Detection Report
</div>

<div class="status {"drift" if status == "DRIFT_DETECTED" else "clean"}">
    {"🔴" if status == "DRIFT_DETECTED" else "🟢"}
    {status_text}
</div>

<div class="cards">

<div class="card">
<div class="card-title">Risk Level</div>
<div class="card-value">{risk_level}</div>
</div>

<div class="card">
<div class="card-title">Risk Score</div>
<div class="card-value">{risk_score}</div>
</div>

<div class="card">
<div class="card-title">Resource</div>
<div class="card-value">{resource}</div>
</div>

<div class="card">
<div class="card-title">Region</div>
<div class="card-value">{region}</div>
</div>

</div>

<h2>Security Analysis</h2>

<div class="reason">
<strong>Reason:</strong> {reason}
</div>

<h2>Unauthorized / Added Rules</h2>

<table>

<tr>
<th>Protocol</th>
<th>From Port</th>
<th>To Port</th>
<th>Source</th>
<th>Risk</th>
</tr>

{added_html}

</table>

<h2>Removed Rules</h2>

<table>

<tr>
<th>Protocol</th>
<th>From Port</th>
<th>To Port</th>
<th>Source</th>
</tr>

{removed_html}

</table>

<h2>Security Gate Action</h2>

<p>
<strong>{action}</strong>
</p>

<div class="footer">
Generated by DriftGuard • {generated_at}
</div>

</div>

</body>

</html>
"""

    REPORT_HTML.parent.mkdir(parents=True, exist_ok=True)

    with open(REPORT_HTML, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"HTML report generated: {REPORT_HTML}")


if __name__ == "__main__":
    generate_report()